{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "app-base.name" . }}
  labels:
    {{- include "app-base.labels" . | nindent 4 }}
{{- if .Values.ghcrPullSecret.enabled }}
imagePullSecrets:
  - name: ghcr-pull-secret
{{- end }}
{{- end }}
