apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  sources:
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: kube-prometheus-stack
      targetRevision: 79.5.0
      helm:
        releaseName: prometheus
        valueFiles:
          - $values/infrastructure/observability/prometheus/values.yaml
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      path: infrastructure/observability/prometheus/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
