apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- postgresql-statefulset.yaml
- postgresql-service.yaml
- keycloak-env-config.yaml
- keycloak-deployment.yaml
- keycloak-service.yaml
