---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: app-dev
spec:
  encryptedData:
    .dockerconfigjson: AgDqQnj9EcBd+a9eJ0cZuA+9vzPa5+GLqw6RJEOTEM+5IkJCkDUjB1fCIP7/jbNr+ppAmsuxMv8zYjsejFRh+uuVK9q9Zhbuykm2Ed6lfuO7fhPE/hTrorXxlW9Q0v+XAi8YhGx0alhK3305ZHUdKb1THowa4CoXdriF7p5RL1uQYMYTzJE4kQ99LNMGpzsLLNyOBETbSa3fMy/3mNKGQAluZnETIqocD7eeQjXDq4CezYxUnlEDGK+F2j3BDEZYUV9dHyNorfrc/mRPIRffYJVyQ1bQEFJkC0D4gIYCNpslQLZpMx8MK1CdewSy4ZsNLIx9KGiEWbnGcvIcmK3lfncqYcQEdWuv597pFOdYxgjbZlake00+WbNlr6i2P0KPlk3MY8ZsOLJ1GjQRqVi6l4Fne0Z/fDD0927Io22ZdGcl3bYRyzL0h2SqEUGxl07gAWc8hCMd6wXVeiIdA2l61mfuDeOaVoA0vDYbu78Trm/IXjc0nGrZme0Vk0Ba+DJsq1YXQzlcdjPj1Q3aBewlV+hfDEqPNMfjcdqHf85GXFQIFM/oFB/xvGlTs9MEDJee0RPu/UBp+NWmDx6QhJxIrsWF9JONay/ZhPEZLYjRBFbzJphnUo1Jlzn0eLWPw27ZS7TQTrqhEBLxwg1MKNaFMyhC84CVB1cRF7U/hmgcNpSy9C9b9Opx1QcQwteRbBLUqEVgyOcScfLgPC8WRXwAs+fTl8bVx3VgR3Yz7ayYBexryXkKfWA5sItveZa84CnppFLeVxrNAtdtGiekSZ2Cf3hvfKHJ/KwEzhzALxjzmgQtRYLxN8SYEmuEvohhlt2VNjx7Zt6j/LL8k/NZpLostSmupAKhv6KXdDEM2SlT9/dpIaQJI/BnbB/BIg6l6RQXMfdjSSnzERoGJ4xajE6rOBDKyu9x9/rmeJ9YPq4d
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: app-dev
    type: kubernetes.io/dockerconfigjson
