apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBkQy6uQ7rfTYBLP5ADvUDKZnuQ0kJACsHHtfrKYTM/mlarZmI3lDG52C7FpyniaXVW+erlQF3KLBnYWy9t+Fb/Z1ghglDL6FU8iIPk6VdHnAoeh5ciG+QRrCXNKa4lE9ZySlvTMnjdhCDAlh847URz/f4Z2QyJr1qESaEhvH8FcvNCnowgHQRtxR/90nEitdhPrwlNLYGTp9xfGX4jWoOTpR129RJE//c1ycboXCJvmWhtPmNEvmDekJYgT8pe1V56rEcrfZTrf4zc8F0vVeaqZld2jROgC7tv1M5Cul+ZgCl/UZzwCifbv4aVEi/emLUx9PsGxumnQVHCtQyENEaRD0v8qKfB4CGtQYnvDC5178vQQjT4eQIeh0CYl/kCdL7sW5BVIvaS/u62NHtLMHGC643lumGmC7Wrz9sEhD3XdFv3Wl/9jTkkT+bid78gUEK+gtxBuTqsoKmag56rAkSWNF2ZyT9oZvng08GDz99Fh6L2TbDuAyoT95oCfWsLrZQ+7sjWjingrpFUGtcnTXwVRzfJHXNU8L/cZZjpXQCXeUKoeqfJaRkqEsOwj/FI5ouHMpz0FjoLEpNmwkEiVVhjkp1DwVBYmwEATrr6+HaXWTkEhB7kXVpMrqZy1HiuwhyxPy0Osl19l4GgxzheyvnzENYtbWgG+6jo/pQS+WAHEZGRNPcUxVXpoBJ1emAKXiVWsEas/YDGLAYeWblJd/jBXbzfpA==
    secret-access-key: AgBAqIDtEtJad8rXOV8Uc3ybq9ip+OjRSdVoLj/PtEItj6k4V4AmIAt9Yn5dk2629x2ZCgONDP/FpDelkD1/BUVoUq3FTEbWa5AN6q71OMoMatSW56fQ7IqTIoTGUnz3vbToYhcvIHR0rbXXx66ji+X3Hk4JbNgT7sOkZ5loSCZTaNDEhBPO+H8kxWrb9z3Y5ku6sMzzkdSXO0xhTPYUXuCaDlUsbrvb+JfBEpGUm/f7q2kfXw960fmdLzzXlvg90B/PILWtay7PLkpvAOEe/7Dl+p0n7NkGvmNwWYIAnMjDCrYA4tbGumxZ7RCnNtIPAnt8JTrHftC4l7bzzMFEzJAdInXJGOzV/Mo6ZFmDy6F2FE1Viw9EjfwtffQnvHhixQBITHuy6HV/61LKxSg+v3BcYwPRYT7OVtE6Ttrog23PKlnjPIzq57sGdJz+JVT1VxHTgFcMBqKRmcc8YCBMJ424MEUU7eGmxEGpRZr+4Br4VdhYbq9HQoRdrIkXns4zDX2CHOw2iyPW0j90qYDf2vPcHfBV6allxathBSgqvX3E09J5+ckLdqMOkcsGYqk3mMt/XvvQ7guIEXIUcEtWEqB1w75pBkJDyRCs3myBeljD7ZX/SwyVjKbSK4IrBSlBJp/1+Ly5qctjfDQ3zRr7aELLeNLXaDUuW/jpUeQoqTIugLgU6pr6YMm0nN2VngdHXhzLzhaNJfPBU8suuz7CgiGh6KSAwOyF+VepVO8MtNqaZc9DQrQfy4+z
  template:
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager
