## GroupAlias: Keycloak group "platform-dev" → Vault Identity Group "platform-dev"
## platform-admin と同構造。
apiVersion: redhatcop.redhat.io/v1alpha1
kind: GroupAlias
metadata:
  name: platform-dev
  namespace: vault
spec:
  authentication:
    path: kubernetes
    role: vault-config-operator
  name: platform-dev
  groupName: platform-dev
  authEngineMountPath: oidc
