apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: koubou-entry
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project
  source:
    repoURL: https://github.com/yu-min3/kensan-lab
    targetRevision: main
    path: kubernetes/network/koubou-entry
  destination:
    server: https://kubernetes.default.svc
    namespace: koubou-entry
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
