apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://github.com/yu-min3/goldship-platform-yumin3
    targetRevision: HEAD
    path: base-infra/app-dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
