apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://github.com/yu-min3/k8s-platform-config
    targetRevision: HEAD
    path: base-infra/gateway-api
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
