apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
spec:
  project: platform-project
  source:
    repoURL: https://github.com/yu-min3/goldship-platform-yumin3
    targetRevision: HEAD
    path: base-infra/gateway-api
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system # CRDs are cluster-scoped, but ArgoCD requires a namespace context
  syncPolicy:
    automated:
      prune: true # Remove resources when removed from Git
      selfHeal: true # Revert manual changes
    syncOptions:
    - CreateNamespace=true # kube-system already exists
    - ServerSideApply=true # Use server-side apply for large manifests
