apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"  # Deploy before cert-manager (creates istio-system namespace)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  source:
    repoURL: 'https://github.com/yu-min3/k8s-platform-config'
    targetRevision: HEAD
    path: base-infra/istio

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: istio-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
