apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak-prod
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2" # Deploy after Istio (depends on HTTPRoute)
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  source:
    repoURL: 'https://github.com/yu-min3/goldship-platform'
    targetRevision: HEAD
    path: base-infra/keycloak/overlays/prod

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: platform-auth-prod

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
