apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  source:
    repoURL: 'https://github.com/yu-min3/goldship-platform-yumin3'
    targetRevision: HEAD
    path: base-infra/sealed-secret

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: sealed-secrets

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
