app:
  title: Platform Engineering Portal
  baseUrl: https://backstage.yu-min3.com

organization:
  name: Platform Team

backend:
  baseUrl: https://backstage.yu-min3.com
  listen:
    port: 7007
    host: 0.0.0.0
  cors:
    origin: https://backstage.yu-min3.com
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: ${POSTGRES_HOST}
      port: ${POSTGRES_PORT}
      user: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # App templates repository
    - type: url
      target: https://github.com/yu-min3/app-templates/blob/main/catalog-info.yaml
      rules:
        - allow: [Template]

auth:
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

permission:
  enabled: true
