---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kensan-prod
spec:
  encryptedData:
    .dockerconfigjson: AgDIR20wprW8EBh5guO1Vl0dCqTseTrDIAS7oQ2fNcMYqQUs1cizdivxEl1pOingfoluCCuzMvE9ovHkXpDxDaHUEjINfh8mpd+VkKMNs39waQPPzkQVDThhLpnvC3EcxwDiIwsWXqrIgS+TgdeDgc263aLADjcl5vwjcf96AhUQo2mOAx/rVl9EEDA5/7CrW15/Ttg68K2ecqoaqi9szBHIqJTPm+gyPzhvEvzR8ufLJojF1Wq54Mk08KCRTw3x1LZRdmFPMYx60E6l/Ba8eO4YMWsXKBTqSGN6/Kp2KwjyDmgLhAPbWsXjfLdl1OZ7HvVLYyWoZ/JqchEVh2yLnuUwKHbIgshdkKbjeJDY5EuzC4OasUPOlhIfZ1zHYH55LKH9b2rzCx6L6igylkqo9n++sgFLWIFZEOz+66rQeZLSfGc+ztADGrnzCmq/6QzoBigIzi8/nt6CLgNFCskJVLzY1DdieziE9W6P/ZvfVXL5Xw5im0/7QtctBDnLKR+YbC89CcSh1EtpbILlrVavlV0+6QEnW9YlojRL5Sy3VkC8E1OZYUdxPzXENza+uFz51BsY3j0vpxsvCW2o90T46ITpJV/9X2DvlsrorH640NtrylX8mBj2MmfIWOJ9T/Bca+8+vlL34sboFimJishi60d9M903uowOZ1Ji2h47SweL6mLjTBpRZrnsOfYRy/xyKDiGzJ/Ha84oKKQlwp2VHxrlckLHkFpVB1HYmaMtSAqy4pxYmlBqYNiIf3iQAYvvF+qqj9+JCAjtaf/upklUUL0Q713URwVCzYVvd87Hbl+71FNMaOwtXAObOV6ef3GsbnIhomnPrFVdt73SjQ+QA9iz8PZcvQ8bMGwuF6AsnI2A1QbwCNz+i/tYDEBZNKOhJrFp8BCUzDSmR6e7RjC0tlt7SD99vl+v6qjT0kfV
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kensan-prod
    type: kubernetes.io/dockerconfigjson
