---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kensan-dev
spec:
  encryptedData:
    .dockerconfigjson: AgAzHyJoRcI/OvmIr96JXhAjqY0tGjv/vjVj/GLSyK8JMmodpb8j2kO3/8nt3OIM15pdATmF4GasVcb25DmZycMol11yFO/sEWNzLSrGbGs8fJia8vUM5Z0FB8IJiWqbA7j86Ohbr9P8RVqyy/75z535uKCsTPefe0ioIJ+5DLdxW1zuqmsYbpBR91hM/2qUhsb5im1e7gerw4ba7ae5jLcDT/0RQ0xA91ZIy3ZijC5SqBTrDAnSWNyY+V/XPTPDl4EhdNZXzXtu3ZrQvPBM9Z2vSjJoOaHcR3tjjJCFQs1jAuGdJl5uys58JmiX6Xfkva9JOqPkIB/59CFPmH3InWv9Bf38KR0qgluRS+exwIwZJRr8lQ9KiAni+RwmkJFXbSJG14G3maAmZKWFOm3IyLHOmUZLxWbUbGYWeU5XdHk7ZDb0CJrb/blePR6xwDJsyYQIkRLTqA7JcWaDcEHQuJx0mg+M4XB3SbkOqIhiIquIuSJlMa6qM/j09i6/wUXogMENqKqlpbX4atOCESZdeEZ51fDWFrlkuZI1LmmJBBWvBw5VXEHgLC6kL4C2/+UBiJC1xgjAz5ZjaQrA2UjmHGnhv/UaG1457sUnV3/IcpdWFylx+6glLrxlWjTIoIE70qda+10VftdGxd4hTp3o45mxuQgrQynpTDc0MFv57nti9GZV+dEQZfLLuIaM+aEcrvkEpqSYEnFyl4ZrJNtNG1PSy3K1smVFxnU0ElD+N6jVQGLAUOCnFaoz+s78JIWOekBYkhdatLialgtRkslmnoE+SBkrMUgpLuVtENH7ngxEHgybLx/Ls2ymGltHBI8WF91nN/svF3b9ouiVWjSq2MsOvMNHlvYc2AwNusS1aeDtutA9ruFBX6KRMjaVQk9HkL4ACiW8S51ctegmdWtdiK4Nv0w4M183zWU+Ss86
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kensan-dev
    type: kubernetes.io/dockerconfigjson
