---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kensan-dev
spec:
  encryptedData:
    .dockerconfigjson: AgCoYJ5tv5Xx5denl2B4MxtWy4mKO1Qf2Eip4JLA77TNuGhbnaFsaZmRwke1qEoY8dNPLGotKxfDgKgdjJiueMtbD2G95SKxh1NoWKYl7O98ykzolFmq6hm9Qkq37f9QMKwH1boQA7bR2JgCN9cLQRKlXFkYQ291Kb99U4vNPp1Ev6LTCF8GikhxvXGA9Zmwj0ZdUOjFrZmR2Fu6OpYcDagiF3JSCSS32x3e+y5nx2wc5CGgacuxRMtm40Jp7EpYe5Jr1qNVq0v8jdDulu24YgYmxTdOpAXYN5MrJ8ZWdEYUchKfxcC/CHTY5SMM4q5dWiJ3ovPu1vbezEJLSueDNdUV7Jxftlv0uZ81jLN0s4BtjuP7yFVWC22Z6IbZDC6cDNCY3RDDLwOBxzgv+iS4Sj6rldCxNIXUdVnwLKNp9c6nWeFiKMGVu7pdGTIIjyjJoC7Hq5jyq6jL4x83Khz/9gQZVJ3Z2i6KndVj4vcqF/voUFv5ufnwiLQ1sZE2qZY/dziKtiWbsnszRvFn3l9ntrK27CRwIieba1es/3pOW6fg+N1v8fjPAXBE1OHtQbuc/B5zPqTjfoCP58qtChXiKwAElfHw1upmp4PVoFdoe00zTcH0m4wrs6Ik+0XRtAH9MfBOTyiuOiOlD6xnCSY7SQz7Nxzr1zbdekRc5hEVhX40NBLjvlWZGbN4TNyGBFdJ9RhRaZURQdBZCcj8S7LnkJuEps5NVyGSUnm/qDrq9UtrYnEo8cfPmtSbPuEwOapOAhAcMBvKf61fCT9OJCt10/iXzKlrnuE07ILQrAYtOmMngTS+2DKLcYPpdekfMlFL7PFMrtQm3b42Oskm5Vtx5o1fu5Q0duoqzKWdD9WQQMjBmsGFxDCXl67xviyavuMcgqVOvH7r7QqXEoiVECuiFR2s53/qD/lfPQJp7fAh
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kensan-dev
    type: kubernetes.io/dockerconfigjson
