apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-dev-${{ values.name }}
  namespace: argocd
  labels:
    environment: dev
    app: ${{ values.name }}
    managed-by: backstage
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-project-dev
  source:
    repoURL: https://github.com/yu-min3/${{ values.name }}.git
    targetRevision: main
    path: overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=false
      - PrunePropagationPolicy=foreground
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10
