---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: vault-aws-kms-credentials
  namespace: vault
spec:
  encryptedData:
    aws_access_key_id: AgAQyekqsSFw2L3cIRfLiGMt0iSEpGzj+wWfyQykd1RNtb4oVjbPeZhJETEmDls/V53OyELI83SrJT1AdTRAaiW2J3xXlF4hvidYTE/bSlaeIwwjthFsdEL7M6hkBX8syDBsr954C/g5XgQl+4aiSG2gZZ3m4dRIFIcfBpeQ8Lc43vLpJwUsHu3lUMvxDHQJWawOJ01r6Dt5wjBUwOsqmA5GkYVXzkW1txd6Be3ioHsLyV8HiT76/UW7QYe5PWJKAK/xq7ftl2kW8PlkWqvWxRR+bjMph3yGZTbHYS9yRsF7I7JmP5TF12hMQevDuxKGmgoRPddFJ/9gXCti4xgJfPusP4ODNuIV3XW3H4YCFJghH3n8jUuKFP+GJk3GuHB+sEg05XXqunTxSedPhuc8nDKyOzhgpCDaANC7TKNUF3WyQcQol5lK9hW199xLJUUEr2TIAagBqbCMhQlMdh4htNEk7anb8kL1bTl5ed3xCi7ae4tKHczqcE3II+DKgoza2gtFe95EQPQBPNw24rlv4lmTNjw9kr/vwHGxQmpK4CPHOhlO+f+prf04ZjhSEls+ZN+jDUsZMQ8SUnf481PmeHjXs5Y8xU2SAWSIhCXjBX2YqVi163Mi30q79twYxeZtsx7UgjnjZie3znDln/q52iKtgffs4QuvpU3XcAEGmqEctCghcb2kp954MF9HdCpa+L+elBc0hc2MjNT5z98Gk8vAQweasw==
    aws_secret_access_key: AgChVFblLGeBKvKJt0g+s9Go4DUp60ki7m6+BVYfDVnIsR2jaJHxHeVyztzBkrh243yazO2jgU81uwOMEhp4GJ/4wOlC0W78emU73DhdKZs2nzUuI/w2H05TEJS3K//F2irOMzYiHOExPr9kCSpULqac1JiQJddCv8j+wr3c0lNwClcSOtDCqrWWvuHJKzOcQ1JrnbSvJU11mbdGasD+nz0gJeIZcwzYwgLPhOUPl5WEAoFv80s0Uju5XmCpdQT3HEdRfUjs+QCOsf20/Fmjziznd5GQQURvHXeiO+l/pcCYvMsC2mqY/o78bnIljkPa/YULfsxFAbA+7o+2jFUeppooO2U0C1RE5QzyLmDnZ61+IL+D3rJp/baJfyVMxIDyoJ20nLOU596bjUzXf4gyN8NdBgYogBm+4aJUrXyGebOig3KiEjcmpGKKIRviCIP9I53+5deY9oB6Y33Ud0WaNrhbSawwSq6pVroSOc2fHXpZLl5tFTGjk5xIB7r9J1mfdBkgCkV7iy9i+pOP4RHHy2+wX7KtiuSc6/6vqt0Nvbq4QhKCVTXGugXBkrjUeGCoUATRzDXfNhdCrr+OUfdzb8Ngil+qBpolprJ+Si4vRvEbLvayYa7NGLUQMGP5qY/Y5PhGvwQkBFDeKjOkQ5DkSeNQaS//d9Q9vXXuzHix2aNkfLd0Vslv8Qj6k7///yqvBokdjS85VHCIq/+do9Twh0SyNETE3ltF09ddh6h54/cjWr7YGZM78+S4
  template:
    metadata:
      name: vault-aws-kms-credentials
      namespace: vault
