apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: feed-google-drive
  namespace: app-kensan
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: feed-google-drive
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: app-kensan/feed-google-drive
        property: credentials.json
    - secretKey: output-folder-id
      remoteRef:
        key: app-kensan/feed-google-drive
        property: output-folder-id
