---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-tunnel-token
  namespace: cloudflare-tunnel
spec:
  encryptedData:
    token: AgBuemtwprJUEnQPsl7uFt2ZKiiQLXN9xmivtiCLpC1CfLTzYfmu5XOsAxiSWlJgn8p5LImX2Vido89vNj2vdr0WcLUYMnNOYRU8qRe4oUMoeU790A3WxTSPOXj9UpRLVN2DlSehp1lFifSNE2nz9R5TQaU5JvnmhfPu/7LpCY9i4+1Ub1dX/JhyjokTIZF6A1tL5HMW7vXZw+9/h+gvllVWDbGCCi89er86XHUmrMVUg/LZPZvh+icuq1o99z3XEfuT+2ZQNvwgph1bpldzwFO5cPPoTmuVWuJDeS7IVT/U6GIDcdYmsTqDOv7sV+5YXQgutrvF5PwexjZIS4nUyXg0o7R+rFY1RIAea3UONpJSd5QygWWGy5tp9QTYmfniupPDRMKwrumNSTsIOX+AwiDQ51utuzbJ1io6VIFsahFviaPP33UP4+thgr+Yf1BxUh00x9tapXFahI88SonW72LfBDKstXQsPCyoQhfCHhEAAWHEOlkXoctXL6cboB46Ju4aNuL7cdSMP+e7BYPaXlj9Ma0Otzk98s5PT7gRoAdxGEPML6m9Pr7j/jGALgTjeMd4B476s+e6BSIpC47+4rbK9Sy03aljV/XQCHXYp56AGsxxndKKdd8T5iEaEOpWbDQHAyZL1V47nL2uO/clZFBkoC+7AxxVrQ7StswaPOALImyfNl6lQWIasSHQQyuVa4sDmB5sslEY2j8WTDbX458zUvEwOMzlJ8EdSIhPPgyAFdltufmCTCUUP/RjFnI3v2aS6L/KLCNEsG4RWFHnquQ/WyoiIHdq9BVjA/yLFXMKgdwi43Ebe/u2GlIUZfBDGeXQvrmTjWqjIFxNPPyo290HBVT1/nBlD+r+bQasq+1SAzAmJbHjTlyUEkXy7/eIgKTiLHAOwG1wXUEnmyNBYe1UvgO+XxGO7IpuYwP3K486kK32seLYITki
  template:
    metadata:
      name: cloudflare-tunnel-token
      namespace: cloudflare-tunnel
    type: Opaque
