apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: keycloak-route
  namespace: platform-auth-prod
spec:
  parentRefs:
  - name: gateway-platform
    namespace: istio-system
  hostnames:
  - "auth.platform.yu-min3.com"
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: keycloak
      port: 8080
