---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: platform-auth-prod
spec:
  encryptedData:
    KC_DB_PASSWORD: AgBOB8YC8/OJoNdruc5C8d8j55BRxebQcSCer/sAUrOauJpzd90pyuw7tIqeeumNxhAK6XUMc2VvZa3VVA5pgWHQIlYAgJHXNrPR5W8CVkK1o0b+DgnPBxpWA+WBPpkFhFQnu/VsMI6r7tfa2V/IzV0HDZSUIhexEBexhCS6grKi0CvC0o7bEzDr6m4csn3G+bPVvh9KJwJuvcEfS7GJamG+/u0nJ6Ca7A1ym3R4yHAp7g6Dg9pmG42kgdziimSgv1QH9mLyNRqTjWX1lrU+oGIHJEfZdd6M8VfMWMlAFhH1c1em477TKbm5p26wUhYZ8I7HNd/XUPexT2gouwedcd7UTiBwSWJ+mUCMXL/6IVbxj8sgCt2k/N/VorwIP/D9UPAWHQw8wwGWEs3zCin8Qgj8jOJB8OjlIbbnYbTIKH/odMis+kYUnVhES2csjiER/aLHwi5sF/nqX3debXYw2VrV8p4q6XPQTU3Nq1k8O+R+4X/2nvQN2YRWGIJbPLiMdFVRjFon2nHbJvjXeyxeyflQdPnjPQvxKMZPHKPY/gV0JZTp/TAjTRYo03RSngDI3/lt/+PZe0y+7c7cR9salPUd+7js/IlPCQhGszytdY09f1+L1U7me96kiayC7L8Tvd+DyA4MKEhSyLpdimI4S4fpjq/Iio2an7D+7JrfgIgceG5UQLhhHjrFNYhfcBqH9Uh2eNiiqH4gqp4NLJ8s3VOEv6JKVBgsUdtBmaycm7DhvZWgGRyS1xZ+Cg==
    KEYCLOAK_ADMIN_PASSWORD: AgBwvkWYmvVhzITWCTvj3hcsS5KpJS5GFhKuMsY7TXddisKUqAHLzLDShi3owl+ypRXizFBQDfLnxtXxNFtEzbPjy+CTn8o+1it1sEFTJyBY/dOLKUCAhk5zzYU7pejH/NMJyoQ9ndeFaMfSlzSzaSMWn8VKRTq0GfQY5vmy/DxE8vCnK1Q77B2AHfu0Q+ztt9yERSjUI/T+lB9IUULfVEUPys8vfQXQK4gG+aMnJ1xmQIlpxt0mxNIP6cZ0g1WhebnAGjEHZ/Q99enw+1DjO7ji0zWzOQNYqLeuG8juwPrrVRvn7I1f20sz0rAmX/hWqe3fyTDYDgFi9E8m2nNg10ENXzD/InTyfC6wscGUklc6TIce8jbKcXO9kRMCTamRQOKVy/gIqnlBAHsVKIjc1PfKltUi8bQF1xpe4d7dgTqkBIdFkipeBbbjiHShn5tV6/69S6GiszE3zaeMKZNSXV1NpIMjCeJWYT70Pdg2YiMa1HFeCoHA5ZY8hcvvNp8CoYySmOU9+4KyHZhYuQs+pPL3ONLAkb5moqfYJJFks4BPkx8r5aYFFmmrL+IF2mx3qxK7nDDm1b4ey3pVY0wh6qRJIIqvDVeAVMpY5MYy2arMYuR3Wy/529obtdoh+3RaypuuJevPOXDinJbX70AWtNSiDnozRMkA5cDT3UzrvBZ3ZO5/MCU/bTnfwH1wxFe8p7Tdc6TcoM/Nbxg5tr3HqcBV3EVACqXhz1/8KsKVVrYhB+OsaElkOA==
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: platform-auth-prod
