apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-env-config
data:
  KC_HOSTNAME: auth.yu-min3.com
  KC_HOSTNAME_ADMIN: auth.yu-min3.com
  KC_HOSTNAME_STRICT: "true"
  KC_HOSTNAME_STRICT_HTTPS: "true"
