apiVersion: v1
kind: Namespace
metadata:
  name: platform-auth-prod
  labels:
    app.kubernetes.io/managed-by: argocd
    goldship.platform/environment: production
    goldship.platform/tier: platform
    goldship.platform/component: keycloak
    istio-injection: enabled
