apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgresql
  namespace: platform-auth-dev
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: postgresql-secret
    creationPolicy: Owner
  data:
    - secretKey: POSTGRES_DB
      remoteRef: { key: platform-auth/dev/postgresql, property: POSTGRES_DB }
    - secretKey: POSTGRES_USER
      remoteRef: { key: platform-auth/dev/postgresql, property: POSTGRES_USER }
    - secretKey: POSTGRES_PASSWORD
      remoteRef: { key: platform-auth/dev/postgresql, property: POSTGRES_PASSWORD }
