---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: app-prod
spec:
  encryptedData:
    .dockerconfigjson: AgAPYO8sugmDblA4eWKpff10WI/L0/E+HuCtVG5hZ4BTSWOPjkCNtBwDrTZXsOfTiWVxvO83Ohloq5y+44kfcak/vWQNh1D+JcEVz38olwHyphxu9Kan0SrldsigVQjaikSYcJlBE2IGy9ejZPSCZG/sDufEvU1IYuzxjNlpR97C+40aq6vMTooeP6wpPW0g2nqqkdlLPY6szxqJte9FZ7W8sL2vbrRpWuPHsmnDbP3B+JfUR21xXMGvSSyKiXlTq7DfgOq/2BFFIDeZcReyd48nZhja4s4O3w2jTRVmdOjlMD5qt4xkVzxbm/LpKLMw6II5dbzpb5FFnIE6vMhhQMuuW7XQnP5FQx4JlhKrmdrBljwHZezXm49a9bWBolWPfzlU5RZDhjjatIt1/kBrbchFQyQlleJ9p9WrfTNWPqoOnCcl8Gdwla/4RkatiFhFHkK204MOKtsNIavG5GAqHszKUz52sV3HNlBCaTnhQY+eG8VkJ4DMemuSpVHKwZDLp4MlLJjy2u/MKEC1J2O4IuzW2mA50sWfjAyqitVtW/zXiCeXfOIsithu4Z52AaRdTohRWdyRQ5LLwnRdY7nO94qiJjN0yqx89wc5BDGKmggGeakvjkrjJktHH3BdCwmySJsfmwwfO845wXZhTPd0NUQK5vxqCurOdCMHIaB0i9E5AMpfsugSq12b6RGuJumIOUdxEWry4tWY5ZP0F+dtZNZSW/RjI+u1Va1XUMDlnvafzYJNsv20eg/CEV7WhYnidBJh1t9Llrkj2GU+u6B07DONPSppeLEPUrHtD+ZYRdTGi/j1FznFHb1t40ua/NchyAr3OoOsgbJOZznl9HVNf+HvvrGQ1hb1bmPb4vJzyEo+AbbUZ1qyhyQDtOT5tQEc7I27rk7DF3ze9efyL7Cdt6CFTFIAFavfsTdNJFe5W00HOx6Ohgt3HgGECqSICoTTGIWa5vd6wf9jkLWb
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: app-prod
    type: kubernetes.io/dockerconfigjson
