apiVersion: v1
kind: Namespace
metadata:
  name: longhorn-system
  labels:
    # Longhorn は privileged 相当のコンポーネント (CSI plugin, instance-manager) を含む
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/warn: privileged
