apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - kensan-lakehouse-credentials-sealed.yaml
  - dagster-postgres.yaml
  - polaris.yaml
  - polaris-init-job.yaml
  - dagster-user-code.yaml
  - dagster-webserver.yaml
  - dagster-daemon.yaml
  - dagster-workspace.yaml
  - lakehouse-env.yaml
  - pdb.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: kensan
  includeSelectors: false
