apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kensan
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-project
  source:
    repoURL: https://github.com/yu-min3/kensan-lab
    targetRevision: main
    path: apps/kensan/manifests
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kensan
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
