---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kensan-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBV5MIX6/2PZ81boMJwLCOW3PfmaLJZ61eEGCLMFl3RabK38WU0jp2AknVsExQURN2VTv8dHzDmDWrDDT+K/LWnBE+xIXCz0Xlda6al1taQP+IGLiyF+G5FM/NHVRRPUK9vfZdWPh4tUB1z5mPVAOoDA2SymapfnGNONaHO5KuF1NU5smqLvJmZhiVZUzgm1Btyg7ZuSzbVOKJJydrPnkeBUtQyXTKxlcd+hHtsbROuK7sNNrpg2N006LfTcyjWfif3PsmNKfW4iTiAHVUqNdZg5j7mC09Gm9VEtpkhceasfR7x1sQgJv7okfw9cfet7r+hSGlD4YRv6jNPEyKJBYIwacOqCV1c5ZugdKhPpoqYAB42+8kanYJi8NUfTYGE546BorpxN2l9qzgzbTxds35YIK9Ku5ESN8ebUhsgc2b5us5jdIRZMAC15UL16KtUdU36mC7ilaUnYwZSTCtCs5S9wj6R2y9SWTcq17lq1ExjMJ5aLAfdlyqC5WIk1LpITZEN3IHflvyT2Z7/aQvf8XGfL9vigQPRf5WMbaV+p3SkG9tT3p1h+ToTk/pHMZP2J93fIMiQBfyGcx26kw/mvbYxX1WK+m/XFjh3591C0cQFHqY4jiS37GCBSEOcfvdeEEewAwolaAIblUgMjk4Mqmlzg9pqJ2mCRF+PV18bBRsBh2N5R4uavx7QYMqZRcMlSkRqen4Asp0YxleZW0xZoCPQygSHsdTxr3gIOeuEkdZq/VBW7L7K361mG25j2ZDD8RmhArVLqSUbewj50B0ONHvdsWBKTEQtmqdI+mPvJkAlfPnaXHxyNE5sdOzCo0ucSFjxugA1b/Ck87LjnvSX8joomnWOseLviEuU90dEZihjJxyKDIsLT2/51YmMQM/coiwmXNfF4S9gEgBAwC/YdvuSFaE7dz3T2iFAKgM4
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kensan-prod
    type: kubernetes.io/dockerconfigjson
