apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - secrets.yaml
  - frontend.yaml
  - user-service.yaml
  - task-service.yaml
  - timeblock-service.yaml
  - analytics-service.yaml
  - memo-service.yaml
  - note-service.yaml
  - kensan-ai.yaml
  - httproute.yaml
  - authz-policy.yaml

labels:
- pairs:
    app.kubernetes.io/part-of: kensan
  includeSelectors: false
