apiVersion: v1
kind: Secret
metadata:
  name: kensan-app-credentials
type: Opaque
stringData:
  DB_USER: "CHANGE_ME_USE_SEALED_SECRET"
  DB_PASSWORD: "CHANGE_ME_USE_SEALED_SECRET"
  JWT_SECRET: "CHANGE_ME_USE_SEALED_SECRET"
---
apiVersion: v1
kind: Secret
metadata:
  name: kensan-minio-app-credentials
type: Opaque
stringData:
  STORAGE_ACCESS_KEY: "CHANGE_ME_USE_SEALED_SECRET"
  STORAGE_SECRET_KEY: "CHANGE_ME_USE_SEALED_SECRET"
  MINIO_ACCESS_KEY: "CHANGE_ME_USE_SEALED_SECRET"
  MINIO_SECRET_KEY: "CHANGE_ME_USE_SEALED_SECRET"
