---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secret
  namespace: backstage
spec:
  encryptedData:
    GITHUB_TOKEN: AgBi8gg0q4OS36FeQzBYkNgviA3+caGYUgwXalo0hw1hTCfKkzTM1IxMXQtUOh0Zp31huwJiXd3/pbrUyiVRjJeWx/tRyPCRZTsFiDAn6BZrsyO9QOygnAhiiUhJLM4eo+8jz6mDzE6X0+4QK0cyoKRm3ux4OmzYlVyYCdbIcck28lTfNPBCW0Ak60M2tr2mzidATqhVm81W0JygFMBndaG62lvDae0ZUPjfZ8mmNtHvRmAXrO3sTRRkAUvQ82KjHXkmsMpgD0WsHsqQ+sejnrCoMsBAH9qqw+gUix3R5Gls0BxxaXUkfXiMF2DV7KQTchA6djuV2e8q8xv+qianOYOkDJyfKMBN6/2+jDphrkeVGb7rUvFLJ/Z5cmZh6pVl0jPriWWgd0cmyAnmRWPylzhfYRrMR9Gca7NL6SR2vmIFb+YkQL2/EHGdjTWrvKZzG2TJiZOMi4P5pr7NlyviYDxj2sOLjCoaRvwFIoPDQ9zPn+ToaO8kKFmRbX+iSJsB2QEP5d0BhyhJI4DENKbS1VAjJXc4pi38t/7RlzbPZGYa95E2U2w8ahYujsq/SJSpjW9lY1cFWWCYnuANZNkCClqna6u7rYzm57Wv6y09b9bhmWatP+9YA0I0KjTLg+KC4QXQj7diNhQcgxAHHON5X+8XXwctFS14TWJi5wnJq2raSauYZvelRo0a4InUp/SUkRFRAuAby3ObP6L7M2AuwQBdKJ32Gu3M2LgVHw9K2blzo/A7QgYnLUZ/
  template:
    metadata:
      name: backstage-secret
      namespace: backstage
