apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backstage-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage/github
        property: GITHUB_TOKEN
