---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: backstage-secret
  namespace: backstage
spec:
  encryptedData:
    BACKEND_SECRET: AgAdDf82DKZER8r2I5KNO00xYHKOZ/Z6a1pAIilsQqmW7r+ktwpf0dFyK6RAxQhmsPlLUFeyyWjWjYtljB4HGlwjm+FvWAT9QkGSdwZadlgoEvNGtFiUBA8RoN69UuCJIEgMTn3FaFXcCHgg1ylr4hr+jQ88m76V9JEheIfkSLcx96LEYbRn8hwUae6/QTxVfb9aIUMdsE0Lx/mX2ldS3AO7krbp1D8y/qG0T7sTAnO64hBotmZNWvXnqM3fntWBdlTZQl9LXWO1oh730fqqh1EhQL+hssxYpJceer9PDBoM/kFO0QVZMX7qGYqeYapGC4zAtk8kICRB+9k0biW7PM6Ncdyl43uiNOhLk2TLUeGGUEtGil2vkig68/74ubf3liafleoO2FzRilb8PoD/8p2yL7/hLFcDasgnPC8wqTb5NVkPCkQXCjioWlK95yMYjQRZUhUBtcdnNgu0E2aK2vAahs3cYToRQVJAjtg3AqB3Gh1L9XA+0cFRmBmlrKyPcKtiwkEGz7FW1Si5XabyoXX2oFTqZ2y+Qmsr2rG/0tVBMeX3LZqbN2ZPxRMGpoLnPbmxyLTybTLgDl3Qjuw5ei2sKZ2YK8OSJ94Q3L1V+YcZ5TiLFBE8SHnYHbdAC5tdHeJpL9LDxv7AOuB6C3vuryv4L+P+Aa+LeP268YKZxL+D69uJaPloo8IKZzAXCtcg4PPIwDk64AhCJyuBB9EglwabC8ELhe426D0Qk0vZmw455CY37O7MbMEzSAQw7Q==
    GITHUB_TOKEN: AgA2nWZGqlNIauHZafjNBcnCGTspp3lF6rjgM62xl78Rmfkm2ZodwkJNn3yHOiewDEtqnlRpoKispTf8GP0CPgUJU4eE7eRKz7ZYplyLmUVpKai1L+QtJcJaNnPtnDzMXO59aIKgRo1fAPzjs8Cv9snEOwg3WOnylk2PzZQ1e/TykOFwPAoGQRyc5BygogTg4MVQoZ9XLtIM9zBj/vQMSTuMRMTc2+J/zqGkPDOntKRqt/y/aV7Vk1g/YTtsaROcb9cFCGIvNPYU5Q3+qhgU/4m2AnhzcJH5SN+bsLN7l0cYgnGCoNjSAHCoNPZfXjvGLQlHm89fA6j/VvRsrULJ799ZmLTnlPvO/NAFA+J/doWIywY+KBzJ+OO6ajyO1QIuUkvCTm/JIYzMZAzCs9Id0irltT6JJK7aDBp/56fJxj/1JI1LoKtM+ogoys2ZBqwxD0cBaAuI2QpdlgfQJiSLF6siPV0/fPBlH0z8yqWsaYSEyl7bjw8iuYlBCVuNvYoBanS0b7esFtuK0r9R+Z+/fW5QtyKnNNoD76YntZtUl0Ti9X2UxsaHfVHY7cNNNyqtgPb1zKqIx1XiRjGlOHaLeiFHqZR35LHrilPzJXqcJr5aYbDuJoYWpnIeCLwELbG0WcWYYKZs2Xc5qyJz8KiEfGSAudsJR0FUfxU1zvu41MM374KXymPtgTldalCAtIhF0b99TMbBm3pxlZ3NMDOhgRuDkvgU5qJGXmjFUp++xBeYuDlORSf4FVFt
  template:
    metadata:
      name: backstage-secret
      namespace: backstage
