apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: backstage-secret
  namespace: backstage
spec:
  encryptedData:
    GITHUB_TOKEN: AgBVvQAu+GwjOJLxpE74y19s+jOR8IFNP2bnODY0SEtjXMFwLLUDc3dOFU3vyc4VAImS+HgdveX1DnPbSZ6WmceNtXILBCM2QHJATcLHx9JtfbvJSpX4nyLVjtIdMGDceKUgSnauHrk0tJbAQz5nY8QzdkV539FuZc3C3y6h4j8D12h8zQqGvXAyBVrH1WBIRXHQGkads1XFJLHOBZf7B4GlN4oxPAtnEy6wm148pln3dnzw01DqYRAE7+Kg8N2o4sIWT68mzu3SngRqbHx19IVnlLsYWJspAioOuSZF5ivwe/YjXo3pwWWvXxOzHteQV89p2TUqqKnKo5NtFZtRS6NlpG5aCeADdadGoRVzAnm9mqp8RULRXTvtG+kaONCPPz3I7EU60IHIlpcWk3E48WAHKIauV6GfCQV6Q6pIIiyD5+jOvyiNETThTq4FHdwYN17AjH6m2QzMoq1cdWnBEqzqklLOHx0f6zXb3aKNBLJL3HHakypMunvCObNmr8OK/x0vjpbYvq4Venbkg3CKUMSNZPljUKwOPgOffTzpE87GYlSgmE6rDPVp6qF70DjtS95pFyl/03Jhgm7Fawn5yoWx4+XvMnlksWkj6XzW9yA7hdSQ9jPa9yiJ4KYXR7njUpuvDFOC930H9aeAkwJdq3He54VK9AFhGOBSHofUdSEOgtiB0TrcYDQRSEjLHT8Uwlp6MOrMyyDIEIMNsjztIsOuJ+p8VAAQB0HyRitMDC84nfi1lmv3m7Jy
  template:
    metadata:
      creationTimestamp: null
      name: backstage-secret
      namespace: backstage
