---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: backstage
spec:
  encryptedData:
    .dockerconfigjson: AgCc9OggG9v/9vF8D1OW/ejxkt7UGNzcL6wf92wZ5kwjfEK8BL6polYcCu6K5TtL0PABCu/b1mu/hTj9xxwk2Cpv6LOPi25Ih/IkavvOH2ZYfIiu0VL8bT0jzxouUbyykpf8SDE3zEHHAVMnr9+4aBf++kIZC27DH4LHCgZR0mqSlcI8eNpzq84p0rqEDLBKeGysDCYY6B8Z4zcEeN4NXQ+GG29jByM38mmOwkE6dzZTDFLfzbfUxqzboQAA1uDoCARjSnrmIGZRcHUGFiJDd0WPhfaJXG1r9fGy7lDGh15fbYt2VG36IXBDWNPF3My5okYyrsahw9/lnQUGslVSyR2g7cKkzelb962s4v9TYnICSsvXQhGbv4uN41Up6idiSaybL2O/7rsDMopeCBw+qfvAXBF+BIK0p5RhRwKQIYsyAjdp0aMkVG/2EWf3ei7MzDwQkf03U9daeYQRExn6sNAYhqGAOxGL1EF5lugpbCtRQPk521xDuYwE3TqwUfZZViOaPc6NJXCXO5HBMW13OFZ1QrcRmNARfxqDqr9DIYLJM2JCBKWbZj9Ldord/xDCE4QDY+Mfs0D9ZEaRlL9j6TjcmCWj0U4wQVi5ylxLJPfgAcPXtjJsEY7hTjDGc+LCmysSSQgDr9M1yhX1G9lQg0tgfxEC+I64jsh+B+1YGt0B1Dy8c6GYNBZmOWtxohBKchhKs/jF0zn0FDCfFkKta98XrgN2/ynKJc9BgAuW32nlqO3jKWao9z00ygaBjEy64PVPIxf4XwvLOA8pQjY87pEefCZ1xbx/S57xb7EuX4TNzFQOtFAbpOqGzULKRxu6voL8rlK3HOORfMB3IarJbvhkvKYHy0hJz00uj3WoiKWDR2zDm2LJsNrt6fGjAI699vXO26odJo+zvdQb1SWeO7FoocCXGGM0EhRt6DQ4
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: backstage
    type: kubernetes.io/dockerconfigjson
