apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: backstage
spec:
  encryptedData:
    .dockerconfigjson: AgCHc/w7+6S7Yqu2ONQFx7p9i5wtBHQ6GhGwoA8xQCpCoTxZWHlqjld1eW6zoZL3ENyarPSf5a930kdSQbc8ISEx4L3Qoa2oKkWSL1qOYe7b421pOqaSxz/sNbhZ9fuBmZwzB2wyrT5xIyEbqyOU9sGDCeCsYslTgTqBfFoxJiErQitWWYDNOA1GcROSW2J4K3lbY97RXiHUDq0zsdBd9PCnL1gS45xiUBErFc1HhmXXDMeeOc/REBOQfCi69wIWJ+2AAlLG75X8I9bwMUQwSsr3VLctZ9OH9FD8+LgjI26bU7U6DIqExWco4OqbOTGWct9lSc02LCKEe5SwNRVfkcb0Vvk5fEZAjPnyBj5nQCMnARUSRy6PajvPVUMs8kGkgSnSR1Bc7+I+xob0ZPiMW9vmG/lpmXjhiomPQtuz18apaUS+9ELG1p4tivECpSqYiLcUR8l0IAP7jlDvpQIuwCmWR2dtLQNgASySZODRKYAtcGooYGzPG9dPnRpZFpJj4JK8v+dDaozEXCJ7ZdBzR58R7GOzc16er40WaK/LEzEncteYrIDlcyUQn57PWbucJPNU1DLTHkgU/FyCodFw7wI/CcQVOphpHffBx1gLlO+BybeNgePJfAhbaBJG/C3jckLUK1ZYuhI59IWKkympbsUh1JNlbNVHqZQ/pi0/c1KfaoI6KSonQCA9a9U+naS6Xd215nZuP2hu2IRr3g9CldMyRP551OldoDim/aanhkIfl/BLpvpitnVm3hcOPwd0oF+Hduq7LQB68rnRtV+T0MV7veGpPvpCdS8z/KRf7VsxmYeW6KCZnm+3VE5yT9YoiPuR06pB9B7+0YeKhy1vt3F1UQ6tOmphR27Coti0njq0UgD4UVoP9Ybkp9TXwLFlFD/0p9ZwOjBURzsQYDjlOWU+2sHbS2k28mTMuE+6lG8UPNW0tqYLVvHTjifml24DMT+I/U5gw6DTjtIF
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: backstage
    type: kubernetes.io/dockerconfigjson
