apiVersion: v1
kind: Namespace
metadata:
  name: backstage
  labels:
    app.kubernetes.io/managed-by: argocd
    kensan-lab.platform/environment: infrastructure
    kensan-lab.platform/tier: platform
    kensan-lab.platform/component: developer-portal
    kensan-lab.platform/vault-managed-postgres: "true"
    istio-injection: enabled
    pod-security.kubernetes.io/enforce: baseline
    pod-security.kubernetes.io/warn: restricted
