apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-dev

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: httproute-patch.yaml

images:
  - name: app-image
    newName: ghcr.io/yu-min3/${{ values.name }}
    newTag: dev-latest

commonLabels:
  environment: dev
