apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kensan-dev

resources:
  - ../../base/app
  - env-config.yaml
  - kensan-app-external-secret.yaml
  - kensan-minio-app-external-secret.yaml
  - kensan-ai-external-secret.yaml

images:
- name: ghcr.io/yu-min3/kensan-frontend
  newTag: v0.0.3
- name: ghcr.io/yu-min3/kensan-user
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-task
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-timeblock
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-analytics
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-memo
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-note
  newTag: v0.0.2
- name: ghcr.io/yu-min3/kensan-ai
  newTag: v0.0.3
