---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cloudflare-api-token
  namespace: cert-manager
spec:
  encryptedData:
    api-token: AgCQxrYjw5h5xbDriTppQQcXEmNscszPCq394WAhNW+1mUJX2ltc/Ykmny+e25PdTWA3b0zaJBJ7UrI4kCgzONJDT8hE4fjaTd602++FW1cj+wUmvFUiZOUkSjtdTUALHVOZ+qK5LVxUmCemXcCET5pRbivhfT9RII+ySifZ2TiMEKJjijO5pOh2m+c+EGgcUEKcKkHIhKkuwl5wXnAwDunsu2LsN865wHiHqT8rnMKZ7Il5Z8bS1Zsa9g8xSsOKjNx2YsxEznxaXkRBDNBf6TtbmDmyKtqDbOrnCIZeaBtAXEM/uTmyHHOnNAnEaFi8FZ962R62DrgvFsR9/he4blHKF5v2OhAk0qs8WyLCQKGLPl93617mXWef9bbjD0JYem60JARquoiI3yHRjwxcjX/5r8QhpKjtdn5ZNsoBHcwme3oXDwFGqI7TbdBDIhuK6RDDQevHszqeAuo9mGLwmEWp2TpJFs6apyvmW05dqPRMxwtpHLi0LG+ar/0yfOqjBY7L6bkohGLoosEj5hn7pV/nX08+YKxmeDRk7ALT2RpHjpIqqCMXX39Xb1BH9evb2FCimER6tW1nVhfvzDavU3mergWt0iJVF0H5GdxJ8Wv7DOoGX7rgSsMPiyVH1y9SHQQ/B+LpJrHL461D6JOXvFuSTFfjENB8jxuHHrZc2zWApukxb7QP6zrlDonoZlXEH2dXAkktq7X8UN7L6I0AW9isCUWrZzyXI8XGGnbSdnhjEvxmCjLleRTZUF+xHqgYWpp9NLOO3g==
  template:
    metadata:
      name: cloudflare-api-token
      namespace: cert-manager
    type: Opaque
