apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-root
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  source:
    repoURL: 'https://github.com/yu-min3/goldship-platform'
    targetRevision: HEAD
    path: base-infra/argocd/applications
    directory:
      recurse: true

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: argocd

  syncPolicy:
    automated:
      prune: true # Remove applications when removed from Git
      selfHeal: true # Revert manual changes to Applications
    syncOptions:
    - CreateNamespace=false
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
