---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: prometheus-grafana
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgCDKBPhPdQRawzK/Z3sxWRspA31YelTXahfKabaG3c53/cj40Xuxuh74EyQYSaMA559V+HrWE9Coi29r6A2X5xkjWWTvEvEx3ZulVqxhiIzPKmk+aSH0NkCVyYKOT9KXCiHUPooDtPYFPe2pLB2yxrmdum8dbUyyXejTpEfiTu4iO/zK99h8YEzoQfU/TygP8Rtn9J7zlnYiIj0X+eKKoH4xQHyqjE3c2JBbT3L1021N5L2knwznMRxYjemABde9nI5l/a4yEGiH+U/ryk1zdkBDHMe6QfUMlWQFw9gvasDuEme6lUuMvG8G0Bx1OL0pgBjM8WTSJVkYguh5EH7XBF1bvYu16TxVIsolSjhZYps7sOVk6LJZGyqLyEztWQ3VFf1GHgQaYaUNx4lctWbIquMv8cst1Mj3BYliPn9opK79U6XAtn6sLfkB9hOXEta0J1ZMcfZ7+PkK92anPxooKAbp8HGFt3CIzBoxFH2w4Ekh15OCN2sYGLh0iCXAQH1YwX+eB9CSeBxAThW3FNq3E3F8+pxpOGr/J+eN5WOhVrGU5wEN17ETMIeXCQmiv1qwkQPfDWhDxkR15Sbna0CAXQ6ez3N6b/BbhiJhkZ4mNu0g2DDREEpqEnLLZwmgF/6yg3LSP6gwn8J3MiUDf5Z9o1pUk6pg0Brv7LmHEG1Sbz5rFQy753yZYnWK62d0hFWE9icPTMkb3sxCMmtwPsDJUKHrOl2F09RP+Oaqi50TD/E3g==
    admin-user: AgCbAQhenxiNUvn+8rnySc4Uzuq/LuFd3r2kcgInIFIM+OVv1GaWZYOQCg13OT0p52s6nr6t/9i3JejGhKepcxQyblmnn3/8AdRt44GZ4Da53CIcx4U4dhXb/c6dgzeB9qtrazsLDMjv4tb9AP7TjFQrq0MpN5ue4ova+DO/a1HvtD9s8OBQPpRfPGZebDE5Nb678DnvGLYxI+Dk9LHn2kCojWJVyNqaADezbv6zSDStaMqBCN3fMDt7Bck1h6kxX/N/U/mcoNOXs0eQhKyaSJWK6bIRLXtmGTfW6IfvVTXAPMKe4U7PuRNae0AvJcY7DeSkYMbkjzpzfatJldzTTcpCDS0BpyNPvUg+D3tlTgn6QHf8uk3q6nEBD0bAhpt5AbV/Wn8UkQjAvUscFtPvnM82JS+icUFWAHZPBIgKfkGtuCsW+41oILN682GBn7VSp8Xy/6H6Nl4FxznIgORAA5u6U09AVWrCHfPSyh87/9/l3Mj9DTjIVxWIwQ3AoQCU5BoOvdC0vinmH6F9Oy8jIscibsSyLpQBvhqGXBq8NHQ+7yn2gSatzgeMnTBDO4qSkSDT6U7WnU20ts3NhOzJOvQf4AGkjZ6F/4p535yaYyHjz769d+EPwofczAcFtUJHOZosfmkhzUKbE6Uy/N6w86toqxrWHjywB6CsgMX+Z1/4n0BYjO5MFl+J6yjsS4QShnZnKdkSRg==
  template:
    metadata:
      creationTimestamp: null
      name: prometheus-grafana
      namespace: monitoring
