apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"  # Deploy after Istio (wave -1)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  sources:
    - repoURL: https://charts.jetstack.io
      chart: cert-manager
      targetRevision: v1.19.1
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/infrastructure/security/cert-manager/values.yaml
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      path: infrastructure/security/cert-manager/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
