---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: kensan-data
spec:
  encryptedData:
    .dockerconfigjson: AgBO1CV0v2A5GA8ad3BjXGmSlpcAEvBh6L9WbXLCKL5+rur6o6eY+/hL9sL5VFF7fwipDS8RdptXab3nOaHe2LqXjFmUlmCaCXe7aIUFcgweGujFfBfJILlzodn4ks4907r8sZ4WHuwfhx6sHvqeDYvaVhQ5hugsRZXSK/cLVDx0umSEF6TuMLqOLIVWUJ70btSxjwvRJONFV4haGVNuKiCbnAH/mZOeQQzty7gltDFGWN638WWyWXZPGh/xu3iFghC4P80DU2tQWMXS+gnDE+dJCyHeRsBQkVboYuLHJl2z5SI0mD7yvJ0Xk7j2ssNVuxedaZ0V3jqwBJLRbuonxzJ1Yls26BSmb1R0DrcrlMMKAtv+nkvpb1stWQ9yetJ71ju6ldeUl/Pk8fass3xBuovdj09ViHDonFvVpIpAwD3v0hO7Qi5+U/RFlBvDSsv3QUGxKv/vJiKYOyK5ncKSG2/RA9nGqHpYQwFsTNL7ifMwk7aRDy6lXF6O8ICV/vamXOVOiKnSU+BIdzlo7jBmaP9UiJQIv5/5ArblXPdIV0pPoQ+5bwsH0pQ7PlSKvhx2zRYn/FEqFq999vVwa8bOuLKuvT8RVxWIYmMsiN08Rblv2Q9vy3Wi8hsWgvPXejVCpCcDiZZOIHLgFNcdZ592Z6n0ZqpC3af9L1CG69eKvl7eKn+z9mC94SAJhRqdnTLUblpnfb45onp5j6Xt1/IeIMlqrNXnu/NGqG+JpC7/AkmWI96k1IsEnovnfDH1yCAtY9AU93ZVPivI32mLCuDKymUk0+Yw1uWjqtiM48hNPzrl+LZDTwbgQdFAlIMQfAUCKADRPJMIQxT0VBwhRoPiROJgbXay3OXQCCgsQsAdOP3g/9fJKrALuh2X9v0DHxa2ZX5meR9qJkfL9Y+lUdKuBCGTTTVsXJKojCtQJxun
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: kensan-data
    type: kubernetes.io/dockerconfigjson
