apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cilium
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  sources:
    - repoURL: https://helm.cilium.io/
      chart: cilium
      targetRevision: 1.18.3
      helm:
        releaseName: cilium
        valueFiles:
          - $values/infrastructure/network/cilium/values.yaml
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      ref: values
    - repoURL: https://github.com/yu-min3/goldship-yumin3
      targetRevision: HEAD
      path: infrastructure/network/cilium/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true

  # Cilium runtime-generated CRs
  ignoreDifferences:
    - group: cilium.io
      kind: CiliumNode
      jqPathExpressions:
        - .status
        - .spec
    - group: cilium.io
      kind: CiliumEndpoint
      jqPathExpressions:
        - .status
        - .spec
    - group: cilium.io
      kind: CiliumIdentity
      jqPathExpressions:
        - .status
        - .spec
