apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: app-prod

resources:
  - ../../base

patches:
  - path: replica-patch.yaml
  - path: httproute-patch.yaml
  - path: resources-patch.yaml

images:
  - name: app-image
    newName: ghcr.io/yu-min3/${{ values.name }}
    newTag: v1.0.0

commonLabels:
  environment: prod
