---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ghcr-pull-secret
  namespace: app-prod
spec:
  encryptedData:
    .dockerconfigjson: AgBfuLXKN2RQEjSnk92SOaIsQEBCktOIBPv7ARNquJTdYQQWihiumCyEVKZrraC20QiJA/hEcyWMfcOXbmYE1tXV5GD739E0Y8HFMB9R7zMbYQ4Syrz4DaIY51kvi4ysH6H0KAAMFJij/nMsm7kBOTa/QzFIvEGL1oa/0F811vHAzvTs/NVeUhM8YuPZy3Hkv0kcCMfxF1OdjIzM+GiBGVqIt1jkKMokeiWWtv4dYqv4s4c1gryrX0CU21z58gpuG1g+sSe5Oddx/Y7xmRx3k6Bv4RwMbr1NGaAGfpNnsOIuV3g1DtJGnbO7kcXjhvg8vMYwy1H39XXjCn5R30UIBjFPzLmls/ucV/+zpcxTHLPDt4quJ+e22qYLwJrGvDylyGfFulpp6eFDwWEjNZlhJD4MGAaMSndCF+1dY0vHFfYa3Zl9oo6GPrmPOPrVBN8YovVo4kJKMTtvRB1GiQP1HQJELslLoKONf4jbu1/WszeeJzaWYlYS13++bEpmY06buNsOdyx6BHoZP2jF2/CLeUfCEl/KQBBCIhQPiDhKziqutf1s8G4c9+3t/G4xFVwHKk8pnQyGnLPCte5RWZ0S267nqx2/3+gSGRq8IqTiaOgLb+VgT29oE/pkV3OvJjPBCX+JUcdNLBh0bzc6iXw4sJEtBa5Rc0RPcgLrqhzRJVm41BxiX6qzZJ5He+IFF0DRZ7l5DL5ru1HTkdwHJcfJ8tmUqWnvdcc9MD4G4/h9Qm/iWRvhpE0nEkqpas4/3ftwaE9wg2cENFZ/XN9AsGnitovirg+aHIa2Yu29GwphbuT0tr/bLS3Cp17psaSqWO2/6rhVNgTrwIU2JTnkbICf2FiPjvk8+qFD7kjw1UPsbrYgLRlpd+JzPP8zElYrvaYasnCu2hcw2TW3YPI0kJ1hAAL32gZHe57Vx+yZYsAK
  template:
    metadata:
      name: ghcr-pull-secret
      namespace: app-prod
    type: kubernetes.io/dockerconfigjson
