apiVersion: v1
kind: Service
metadata:
  name: ${{ values.name }}
  namespace: app-prod
  labels:
    app: ${{ values.name }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
  selector:
    app: ${{ values.name }}
