apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: keycloak-pdb
  namespace: platform-auth-prod
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: keycloak
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgresql-pdb
  namespace: platform-auth-prod
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: postgresql
