---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: ghcr-pull-secret
  namespace: app-dev
spec:
  encryptedData:
    .dockerconfigjson: AgDXZ13D24wz/njnMonVgM4ixlR0Rp4Yt2CsLJnyO5rKXzFvAS9RvK5lGl5OJv8Jgiv82+f6OgyEgLAJVlMNCV9ZLbixhFcC9TUrMkT5P/0eXNJNjhMGzDFtcITnzF9NThTiFia1yNTkjJ0Bi1HA9a1TvNncCuAq6iFMDG0kt+O45F5hAO1+rM6KsGKMrraDfbHJ92te9pojGpxkZdvq5RC9P2NGJDenZHUJKM4GAe+9ry12IIHXUWiPr1nzTcn04gxgOXSQRBgrL160SJxQOHX8FsC06GhHiHE9GweeOh8GrbpqdxvyzQ9jKQmsqnN2U574S50SysTd8TV8Ar8IvEMjgeQfD9iQMVbilBXpQpHiHMxiSujfNSBsyG4/9CyLz3lLhazxbLrXAEnel/eVElIZlNLnIqg6k2Kw85VzXdGUC7WmbnHO8TTzJ+R2Ie1VD+JePEkmXW5TMDqzrKxo2I1V+EUveeUImUpG2224XTxPIwOsx1UOnlVOls9NsIqdyKV5tnirzhOrdJuTPs254iqnJnmIAbHntDZhE0AsiwpGRKFpWFXTR4o7d22FLq7grIV/+A5T0Yk3oAhWKosOCTI3nlbkPDNuNUfRs5L/segdwDva1T5D5++D4K+xuPD9xvX3D65ILOxWBJR/xfLOXBOHhY5LtSMTaQgUAy6iCLNx6GrwmKEu3h4fK8/wufrQ6eQdhvAqQ08wP3clEmb24Gn6pyAUY34gI+YwnO3I2WwWdJibGmlKScnqeBvMt9jt0Uuiy4i+CXZBFIH5Gp7hSQcIOguVyOfoQ3H5hpBE9UoZYw6iMqWUwCaFE+wE6lN18nZiWfExho8DHw7MIaEgvcfhUjb5eXaTuZoQeh5BuAXoKrrESxWWQsyU7Sy9SdjuyTm3/OtB55OLtOT0LKSWQoNpRfVNq6j9KX8FmckhjgdcUwt9OMiWB5upzE9PL1x3jeWBF4pN/DZ+ptma
  template:
    metadata:
      creationTimestamp: null
      name: ghcr-pull-secret
      namespace: app-dev
    type: kubernetes.io/dockerconfigjson
