apiVersion: v1
kind: Namespace
metadata:
  name: app-dev
  labels:
    app.kubernetes.io/managed-by: argocd
    goldship.platform/environment: development
    goldship.platform/tier: application
    istio-injection: enabled
