apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: otel-shop-demo
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: app-project-dev
  source:
    repoURL: https://github.com/yu-min3/k8s-platform-config.git
    targetRevision: HEAD
    path: apps/otel-shop-demo/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: app-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
