apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: backstage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: backstage-secret
    creationPolicy: Owner
  data:
    - secretKey: GITHUB_TOKEN
      remoteRef:
        key: backstage/github
        property: GITHUB_TOKEN
    - secretKey: AUTH_OIDC_CLIENT_ID
      remoteRef:
        key: backstage/oidc
        property: client-id
    - secretKey: AUTH_OIDC_CLIENT_SECRET
      remoteRef:
        key: backstage/oidc
        property: client-secret
    - secretKey: AUTH_SESSION_SECRET
      remoteRef:
        key: backstage/oidc
        property: session-secret
