apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: platform-project

  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: 1.7.2
      helm:
        releaseName: longhorn
        valueFiles:
          - $values/infrastructure/storage/longhorn/values.yaml
    - repoURL: https://github.com/yu-min3/kensan-lab
      targetRevision: main
      ref: values
    - repoURL: https://github.com/yu-min3/kensan-lab
      targetRevision: main
      path: infrastructure/storage/longhorn/resources

  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
