---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-secret
  namespace: monitoring
spec:
  encryptedData:
    admin-password: AgBEuGGbh6aguafiOicRI5SDzlfZvk7piTqpyBcBrYVUc2hWdm5ccdgIU7i9MvCTRI6eIDr52GG6MAHDRw58pQY+n+SEdo2/BYOyTqgzeg3DNlPBrdNuTiTF3yeMNXIIevoAFJC4qFoZ0vKdot0b/kLoSL9KwevP20XXrhtRJdWgTCb4X3bR6sF3jjgUSiY0tZw3Gwlk3A8e94M0sbfJuIPl9ioOM7z1DwvdouFgRmzzP/lTL5navfAJ3zmATwujy9S6SyEwXa04smTCrMaq2WQzxKC3nLr0nzdA8SSMNfbLAHQ4rmaGKJjhATO05mLFl/SA7AwhOQi+h5g0uAeoGOCSOhfbnfQxIyhfDyBkbl1mK3ErQaoUPUq+q3vMa/ULkbWrQePXDX9p5ajgmGFUJfIHK6WI6Nbcm7AlaYUz81L5ZPqCBEKfPXXoN3NXlKeh8L9zETfjE8DUytTEWX49HcCOeaxU1Mevx95AodJmRuwbb3Nkg888lZds5f6Ih1h88+UXsBuo1jRS3K2CQraaG4INHLUQiwIxjYW7Ub5bHuvljOK1D0/0YyX5TB+P9IWKgOaWNIL7p400UXAN1iyiF+QrO9/MUIUZZejE83u1T5ZUBiVV0AQKqitltBGyo2V6mW9yzN5lXsZKYwhoqVH6MpZiwXrtoC6rZEtvY/kFRUex9O+atC0/jc5y2SC085EuJ0CGflEpgJXLshG+aIw4KBtCelTFDha6+WBoxhQwYSADhw==
    admin-user: AgCRHyzjDjChFQPczUoXb2qci46xpsuPU3+TCpaNg79XKz3Q+ZB6lK7inTvQBzYxcsFHH91TjcdnKyO1rA6AarqqXYiNA+YG/teQFAU1lcE66Si6o9LGAWBnT62YiLB9a6AXtOaAs1wQvJxcIsuf2fP9XjbFnEW6kggjC1zA05kU9snUDLv8k4+gB2mnVqYOtFkIpOEtuewP0b4Wk2RSC03/qnECDE8lMFogLx8An0CTNCiYmxdIhH8BXezc8c41fVapqhKumz3j0Xjo7g28npwe8iybZH7j2KMxvr8PaPp27LuPucl7/XBBvrkdcH0S6erJdf37b54AcTKFGt4RgvuhhWpA0h/Fx0s/GgZh3uAOggwzXTo8920TITtCxr3mhaTIl0AM73j+NtrjTqycdwx2s5znEhQSerslcLaLEjlW6Yi+ApM3RomXwRReKjM/QaYxCJz+2l0OG9hAJRANBsK2hKq3rObJHaCxc0xuhtJlQca8T1yexIhT3uA98jiYSglBlVt0kY/CRP93370NMmTD1It2jLAOkVh5ddc3VIhRnI7nyFZiYQ01tqyOSgpOHhksWX5Qb7iccy7vkPjyzh74VuSB027G6tMQGkC+f4MyEDhF1C1KNDqzJYmhoFzDbquZ0SZP8NlBBIDtbsJMgjMR1w+OS0yrOIKJg2cHSdeehMa6u/sQHREEgiveZFvGbj4h5QwVrw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-secret
      namespace: monitoring
