---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: route53-credentials
  namespace: cert-manager
spec:
  encryptedData:
    access-key-id: AgBdk9Oky/rK9SxatWNm+6be3h38mppAhjdX17UZCg3NaLoOQpqbNUmoL+MVKWR9N5AaOdIZjf06sSb0r5UXAkp0F3bmT3deilOwBGjW1lrqC9aTp3/hy/vVodaJ3xonE86hHp6Lq6jGX9utVHdrkVJ239BJ5h8P9fjwNaz33z+EJzL44Q3CBBbnpm42ljGM211tNknlKWO7A9j6x7RB92dfyCNX0ds+F3qoM474U213vaoSfiieAB8IRAmp/9jXKvkovH0OT5J/VeSP/SUhfybaK21czhy40H2bzTjpd4oyzn6+zoswxinkhHpfLHOmEBDvjXa5fvLGFGj7PNzXM0CJH51h27sASQSqcE4yhZ60ZAq235yLcTfXMocsiv0wK7FZJrbHyXjOD3EIdOZ01MWc98EAa98pl4VkbAoOs24hdc1qsiMz7Jw4L83Oj9HeOxelclg37JLi+Jjs8/+1XBbkeq1Nr05yb8BYzrjzF03PX8vI2YPldKExz+BxoLTvc1OEiqa7YDlvB0Y7J2efyBgCjWjNd4H8hyNCSFPJfgOqDvTfFAhaVImXLy9rAlUXKQZIMxwg3ECsnBvKbhkKOBTHhj1meWMnKtzxKqQFV1U5XKxhOtQ7UzwbT5Yf4JGPqP2tEHEguB5C8GLeX60aN5uz4zqOo+x7VAxfeYyigoqr4Twc025VjPmyWduk8f7BrGXLQ0bXP0KPp31vaqzkG1X3lttwWg==
    secret-access-key: AgAvTvYStb/HMLD+00SGov5Ap31v8RzCnM69OTQ21VpSKCG4eRM1ESYyLfCXT2/1sU7jC7D10zbsvZfJ549IuHefYexqLQZrEheJO2TMMPHKD/N2TOFkfLsqi5IqV4POKhC2HwdzxP6Gg0sMTBf9lh1A19GgF4MhAIatezWFAPSxFtqg41W3beqqvdfMdthPsqFESbO/zYN4pskwfXbT0hn4hDTFu9FsACRakIor2EbVcOdgvPvSZhicZhYGNFIueM/95GVGokRcYly0TBGaLM45VlBc60Q2T975v59zJy1EnvwQ7k93HyZOi3LWseW3K1KY4ej9VcAFcNmprcwlB5eknKwf+jiYaGuqmf+LT/grKab/fH2cqyCZ5PsvR6FDDC+Q9uQ30hbIAIOby/nTsxkl8kMEElaule7S5JVoEPEd4aLRYE46FR77F8wyIPXScrYLiti5K3D2s4jHta3uEOFwC2eOiCCfLauYuievN68Q6zAA8vNsKj8hs0BXu6PWAvnaWDB20G4PfxgqCqpfZP5Q9r4UmXLca+ewWMX4NxroR39nx7GL9dQWCLF14GRd+uxaLll/u41K5GUbIiqmqo8ayr16sWjRzI+O3Pi2BDHnXKS/gbIza+SLoZj9iQacjD5bNVOZiEA5xUJYDsCR8izMrIWRQT+X+XWYJd4pHlPcRpIuoifLMJnebplR9WKd4jGHJFcdcDiq2B5ZS65b8R1Zl0KCJ0ESa43Hv9yMWVmf
  template:
    metadata:
      creationTimestamp: null
      name: route53-credentials
      namespace: cert-manager
