apiVersion: v1
kind: Service
metadata:
  name: lan-dns
  namespace: lan-dns
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
    service.cilium.io/type: LoadBalancer
    lbipam.cilium.io/ips: 192.168.0.247
spec:
  type: LoadBalancer
  allocateLoadBalancerNodePorts: false
  loadBalancerSourceRanges:
  - 192.168.0.0/24
  selector:
    app.kubernetes.io/name: lan-dns
  ports:
  - name: dns-udp
    port: 53
    targetPort: dns-udp
    protocol: UDP
    nodePort: 0
  - name: dns-tcp
    port: 53
    targetPort: dns-tcp
    protocol: TCP
    nodePort: 0
