---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: alertmanager-slack-secret
  namespace: monitoring
spec:
  encryptedData:
    webhook-url: AgC/nBF8oVrp9H9XuGMnL4jxErBID6qK0kFcA+fiUWP8MkAtz8DHB9Vv55PQyvaN1tds1neUkSc8noYEeFPf2mEOGwZ7rUOoqSXkVBidjG89V5NJKCE7laNGAU5rDcL/u3ooEZ90NgjflwL+xuw5BuT6nDFsbXEArfpQMXVYRylXN6yyN3jfHuNgz/xAq1bFkwe8WXCVxvnYfjmVZTDdyJBE8LRc0Evi19Rjs51AbHxDZFFhtShxO2D1jI5DuOXA0pAHzOBVO5B1Rz9ZT26TMWBojZRZe/fdKUsKi8uJzTOjRoA9uhNfwKq96NvAL9IJt9+sc3im6w1/KmoCbDsaNUF+FlYy1JZmgbaOnNjAH5iE44r9slO2+FOZn2HIYoh56sI1a0aix54FK5ByyjW10/VCoXPQHfACB165YXvpUEB2jBlWOlMCbujYjvK1u1i4RZOljvQjyc/5K2b7qxVOiPBs3bTlqiTsW71nSmA0Hk0Xo+m5hKr54drk6Z8mQnOyb8EozQ8YNQN3i2rUJ639nq4YHkchYn8+M9IaC+xRhMb9EPqvp1CK0eu3N1hdVqUiY6fu+uG1Ua4bYH1oDZhNibuSgI0ZcQIDRXFJPKMov7d4W8avinRmhkt7KDMhEalOCS05S6L2kZfAx38x7yLU2wvU6NgCyFmV0S/4gntqBHCUbL517vO1eJzXwehzRK2PfnI8eoLoJD28vHAhYjKXq5nfn0+5ac5FC0DMRfPDM7xyHR//e+CyyS3kbbFl+TjHFH/Pga9F47To8djOki5NlKXZqnGgDOcWiVz6s/CoEE4d+i8=
  template:
    metadata:
      name: alertmanager-slack-secret
      namespace: monitoring
