apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - postgresql-secret.yaml
  - postgresql-statefulset.yaml
  - postgresql-service.yaml
  - backstage-secret.yaml
  - backstage-deployment.yaml
  - backstage-service.yaml
  - httproute.yaml
