---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgresql-secret
  namespace: backstage
spec:
  encryptedData:
    POSTGRES_PASSWORD: AgBMP/hoLyvm+IS/OenQO0OwwCimWKt+raG+DAbDVuMfEfUvHw0ERDgPDrrmsUzsDaBjnwSGOi9XRAzgCZ4/5Rat2Fm1KrQEByARYyz966Pgscy4eutQOomPikwf+87AsM4pWor5OzWHtwsxf83KetGMnfXFjwaVXXIrBnpMiQZtL+iiWMPYTFowvuM0UWDdzj7S91e8Vn1vxPnOyyt6vyrbYLCqLmCsulUwjg8qBm1q+kEdIGr5+yAMyBGrsfvlUf/qpGS0kBPW1iDq0dHuGe2Wj6V0YNCIkwhAzUoUUF8A/F9BLOE0CrS/6dDYTBLpT2ijQvymW2qSUS+dEqKW4Rv7Nc0n92PVOR86Q+0IQO983rl7ttZIvz4ps5IfkxPaKdk4MjA4bl/rFtMas3P4ayIgki2VXjFv+7KMmq4xQiHS0nErlqVsNmATiiIvzsJU+qmx5DVpl1rXJ+tH03kha8l53k3mUtEAlVF7C+btntiS3jdgHu8Mwa8pu7UUhh/+WcHzA6LPXA5T+CiusXYJ0TOh43Nigy/LEwhPWQREB+huUxxhzvMc8vOxdQG3KGiQ6W2C7Ub6geZNFTNRbMIaX5j4rBeN1Dx8wRXGUdYybDn0kdWaBsrWMbwOBfu6BqlQlYCQhisU3oOmbUtPlhUHl6nTqq+BLj3X8hT5eGy1CHGCJv4ycAoTxphZOwrbynr19wId4zVxIcUi173Ax6+A7vtRw8M2bg9V8l+3ViOlKpjzfcNk65oW4fEvh32ZRg==
    POSTGRES_USER: AgCFi7f+OlDS53ETn16ACjK+0JwIK6OQGvrfXmWCKwONoK/c+awwHgS1RkZGxcDC+lY/h+dZidXFjejymfAaPMzqBgiRZ2bR+s8zN5SnbhJ6RaxEviG9qDz63zbnupYZT0s0ZfjHAdLdKUSrl5se5uD2B0D9smgKFP/Gpt23xkjXvFEXJGkQjXkryd2mq0QGKKhN8HdklsU1wD2bTI6kaCGxJIrrC25AfAxooQSqT4OsLMWBxzJeZ5l+45ItuBM3NPBwtUebgNJQkgF7q647J4Q4EdUzFPf41ijbJrNfuQp7OHYBRChYJVnYi/6GyQ4Btc+QfgS/PMbhof+ZW60lmRqmVdsKY/egmNGGpX1ioUeMjBlu9jwJ1kJOshb1vnbpz4owmYeVaVhmAbURsy0qGOiaHbrHwrr/1Y0A+2x5Nobl+37ZBaxpOAqIdUlq+3euw4TPFupaMvRCPOVfLKQv7leHeg9Ssz42MQIs+0Wpuuq/il/WqeP3MHT90jNS2/tZUSi7Baf3Cv8PJaAIyAWkQwS9KdGUReaExM/08z1Fhln5y0OrnPrjKqH/Lorv35zmAbTl/mb7hw7Z3BkaRiFLzeS7r5OfXywZlNHCdLqcCrBABFS2F/hgrQjkogmzCmRJ3s7stbJebQhC01P+4wTPOyqFn48oMeamupLdz1eBX/7nlGZEkTQykFRazkNYKgUPM9/oEq8sTrGdA9c=
  template:
    metadata:
      creationTimestamp: null
      name: postgresql-secret
      namespace: backstage
