---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: keycloak-secret
  namespace: platform-auth-dev
spec:
  encryptedData:
    KC_DB_PASSWORD: AgBa7xuuAKwMrgKw9dB+DccpvSePGAflE+WbFBe+xWvx7H1qwhJb0ApoukXnKI/NYw5tl7cD9NENx1XOq08MFMu38nlK0prhuWoht7m8slKg3fgCYL3cSxvWruRy2AcSMDfbprsFrTp5AlhHGeOosvPOmYM5MLtxDug7hQR+nlRhL//LHvutxIfeXGvJGITi0QIss7H8JeYYeuAzRPrwqRkkO6vt6i1WN0JqPWm12bvFvzy90LH4HitoPfqOnF64n9KrvhaSUk0eEccZTOwCDZ73q37RenU6Ox5n3F6+yt5GyALrwEv38HzOGVdQ44ptaFv6aukdBOXa/CFDdHnY+Jb8Tg67kVrmRyNDk5sFO9+sYWXWrxuqpLtbL1fFhIuciYLYbvL/KE1UEb0QcRMo1JxEjAM/rYdJYhaofJg4yq7nxc6jM/MFd37NsqofEOa//Z/LmTWk+8vkukcxqCuoAfKVbJOwtS35pcmAeFVaRzCnqxXjBF8Y0iIESnIBfhv/i3PS7DnY89OLYyRUQpr+TvrxiOBgcnsALZm49Pm5NvSlPVpp3c3Xgp1Myug73SIltMvUVj/O9U5SrfgN7Xw3bOgGHwGS6m3dQAeVHi93z2/dJsg+VQzBarRmKNJ3YRgxC12Qc0bKa6/uy3iWEF7GWH405KkjSSstRnhH0TyFQ5oJZUZkY3BbjwBjTGAcHxMUqcL2wLURVvXMCuol9Y4KG8mCBlpXeelkeeRIwTxFlXs=
    KEYCLOAK_ADMIN_PASSWORD: AgBLceGFa3sO8TVXJQ2rIbyL4oKWBM3A1100xk3V09ik+YEr9iBawtTP5AFHq+npuO82AMvqyCE/1NLTB8A0/Wijgoakwh/TK4U/NajH3sIhYCKWbwMfkxtMVuYGUOxhuwTfR+IrhSHePLj0RaN45ytMNXll728I10bxMRljGh3BrFTV9CZc/9fKz+SCavQ5EuBA/YdW4oDRZZ/2jbwdfytU8Fep/A+n23BjFrQqPsVRQ/MOKs5ibP+xho1C32p8tloSph65TcLyfdmO5klohqB4CUGI1VBP/xnr1S2OXfzcB1yMehg6KjKHW8+PCKB2GyypTHkJDz3VxfGW9PFXNQ7doMFBN9LfqCuO6tQUoTj02H5OVCISIqSEUBx4WCWAebkmtD4BI50GalRQmMdqrcYkknUEvAwSS3oklEnlzXtHvREwIkFsaeYeGp12b5zqPewXl8K17vGedY2NYxdF+eoyHUun5UNDJtKohTWWHWQt1geHZb6/8Wx9rsfZmJ3NwxeRq2JgLXziGH+G1He/JltAI4wNX2KpDR4NFkiAVaubrGnYYMVr0dK62KejocrMhvHQK0QNstMeYcJIo5PYWHFTRbzUSsndAK5FYEfJKeqTfoyf7m5Oe5B9wYDGbTiL+mcbGeqTFLGWYYva84bg/mX1iShp7Z2VCopIW1p6aI6g7ruPvRBfJ3FsqPQm5lbhZtcd4QQCbeqt/oGlqG/Ll2u72tY=
  template:
    metadata:
      creationTimestamp: null
      name: keycloak-secret
      namespace: platform-auth-dev
