apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: platform-auth-dev

resources:
- namespace.yaml
- ../../base
- httproute.yaml
- postgresql-sealed-secret.yaml
- keycloak-sealed-secret.yaml

patches:
- path: keycloak-patch.yaml
  target:
    kind: Deployment
    name: keycloak
